# Generated by Django 2.0.2 on 2018-04-26 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True)),
                ('time', models.DateField(verbose_name='time published')),
            ],
        ),
        migrations.CreateModel(
            name='FanPage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('time', models.TimeField(auto_now=True, verbose_name='time crawled')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='fanpage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawls.FanPage'),
        ),
    ]
