# Generated by Django 2.0.2 on 2018-05-02 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='fanpage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Department_id', to='crawls.FanPage'),
        ),
    ]
