# Generated by Django 2.0.2 on 2018-05-02 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawls', '0002_auto_20180502_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='fanpage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawls.FanPage'),
        ),
    ]
