# Generated by Django 2.0.2 on 2018-05-09 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawls', '0003_auto_20180502_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('time', models.TimeField(auto_now=True, verbose_name='time created')),
            ],
        ),
        migrations.CreateModel(
            name='PttArticle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('push_boo', models.CharField(blank=True, max_length=10)),
                ('date', models.DateField(verbose_name='time published')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawls.Board')),
            ],
        ),
        migrations.RenameModel(
            old_name='article',
            new_name='FacebookArticle',
        ),
        migrations.AlterField(
            model_name='fanpage',
            name='time',
            field=models.TimeField(auto_now=True, verbose_name='time created'),
        ),
    ]
