# Generated by Django 2.0.2 on 2018-05-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawls', '0004_auto_20180509_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='pttarticle',
            name='url',
            field=models.TextField(blank=True),
        ),
    ]
